### ISSUE TITLE
[SEO] Improve presence and improve access to documentation removing old stuff

### ISSUE THREAD

**Issue by alfinal** [RetroShare/RetroShare#1545]
I want to help to improve on-line presence of RetroShare in order to appeal some new developers and collaborate to improve documentation in order to help new developers do their work. I made a deep research and taking a look to all resources that anybody could find on-line.

* We assume that https://retroshare.cc is the only official main website

That's great, because [retroshare.cc has a not bad at all position in Alexa's rank](https://www.alexa.com/siteinfo/retroshare.cc): 1,154,294 currently. [Retroshare.net](https://www.alexa.com/siteinfo/retroshare.net) is much worst plus has not a valid SSL certificate. I guess that you manage both domains, so if you decide to maintain both (that is a correct idea) you should:

- [ ] [redirect retroshare.net with a 301](https://webmasters.stackexchange.com/questions/30938/seo-and-multiple-domains-to-same-site) to improve SEO, and, of course, fix retroshare.net SSL certificate #839
- [ ] also is a good idea redirect https://retroshare.org with a 301 and, of course, fix retroshare.org SSL certificate

I also saw some other sites without a relevant rank and just with out-of-date documentation (that also have the problem that confuse visitors). I suggest to do the same if they want to help the project, maybe they are reading this issue:
 - [ ] redirect with a 301 http://retroshare.us

### Time to talk about documentation, git and tracker
*It was previously partialy mentioned in #1080*

A lot of years ago you moved from sourceforge.net to github.com. I think that nobody doubts that it was an upgrade. Some day will be the day to decide if move to gitlab or other or not as propose in #1279 [the code already is in gitlab.com, not issues or merge requests](https://gitlab.com/RetroShare). (Take a look in Alexa's about [popularity of github.com going down](https://www.alexa.com/siteinfo/github.com)  and [going up to gitlab.com](https://www.alexa.com/siteinfo/gitlab.com) in June 2018 when Microsoft bought github.com). Anyway, currently you're continuing project management (documentation, git and issue tracker) in github.com and not in sourceforge.net so you should to take a decision about the way of document it and exactly where in order to

 - [ ] redirect with a 301 all documentation sites to **the one**

Currently we have to:
 - [ ] move http://retroshare.sourceforge.net/wiki/ data because has a very slow and pretty unmaintained wiki but still having some useful multilanguage data
 - [ ] then 301 redirect from http://retroshare.sourceforge.net/wiki/ to **the one** 
 - [ ] 301 redirect from http://retroshare.wikidot.com/ to **the one** 
 - [ ] 301 redirect from https://wiki.cavebeat.org/index.php/Main_Page to **the one**
 - [ ] remove wiki content from  https://github.com/RetroShare/documentation/wiki

* After my research I'm almost sure that we can assume that **the one**, the place where all documentation should be is a mix between https://github.com/RetroShare/documentation where the code is and https://retroshare.readthedocs.io where the data is rendered and showed

So in that case I suggest to 
 - [ ] change all places that refer to  http://docs.retroshare.net to avoid the direct use of retroshare.net domain
 - [ ] merge DOCU and WIKI links appearing at top of https://retroshare.cc/ to just **the one**

All of this are not only suggestions I can help to fix them, if you :+1: and we standardize a way to collaborate in this kind of issues.

### Extra for improving in the next future
We realized that any kind of documentation has its troubles:
 - http://retroshare.sourceforge.net/wiki/ is slow, centralized and requires to maintain a server
 - http://retroshare.wikidot.com/ and https://wiki.cavebeat.org/index.php/Main_Page requires to maintain a server
 - https://github.com/RetroShare/documentation/wiki is centralized
 - The current best solution https://github.com/RetroShare/documentation is distributed based on git and doesn't need to be maintained, but... is not much user friendly as a web-based wiki

So the best solution for the future is to
 - [ ] fix issue #29 about build a wiki in Retroshare network and use a node in retroshare.cc to publish it as a website with the internal http server as suggested in #989

Also will be good for SEO to:
 - [ ] Move blog from https://retroshareteam.wordpress.com to https://retroshare.cc (maybe blog.retroshare.cc). This blog also could be a published as a RetroShare channel and shared to internet with the internal http server as suggested in #989

**Comment by felisucoibi** [comment]
Hi thanks for yur ideas i agree with some of them, retroshare.net don't use a 301 redirection atm???

"Move blog from https://retroshareteam.wordpress.com to https://retroshare.cc (maybe blog.retroshare.cc). This blog also could be a published as a RetroShare channel and shared to internet with the internal http server as suggested in #989"
I like the idea yes and is very easy.
retroshare.net is not controlled by rs team anymore, or at least not enough controlled.
retroshare.us is nto related to retroshare.
rertoshare.sourceforgue.net is also deprecated and unmantained.

The changes in documentation should be done, and i think you can do it in github as a pull request i think.

**Comment by alfinal** [comment]
> retroshare.net don't use a 301 redirection atm???

No, it doesn't. If you ```wget retroshare.net``` you can see that uses a redirection that is so bad for SEO. A great way to make a 301 redirect is with an .htaccess file, i.e. showed [in this document](https://www.compsmag.com/redirect-site-using-htaccess/).

**Comment by alfinal** [comment]
> The changes in documentation should be done, and i think you can do it in github as a pull request

Of course, I realized after my research, but I prefer to confirm (and I suppose that much potentials documenters too) that the official and updated documentation will remain in https://github.com/RetroShare/documentation (and not in https://github.com/RetroShare/documentation/wiki or others places), otherwise I just would contribute to the mess and I don't want to. I want to help. And a lot of people want to help when see places tidy. So let's make things neat before :relieved:

Confirmation from at least two official developers with same criteria would be great.

**Comment by G10h4ck** [comment]
Sadly the only domain we control is retroshare.cc, the other domains even if redirecting to retroshare.cc are not directly controlled by us so we can't configure the webserver for 301 redirection, about the rest of things I agree. About the documentation I have been contributing only here https://github.com/RetroShare/documentation and the inline documentation in the code, but I think we still don't have established *the one*.

**Comment by G10h4ck** [comment]
retroshare.net is controlled by @cavebeat which is very difficult to contact with since around one year (at some point. retroshare.org is controlled by @drbob which is as difficult as @cavebeat to contact with, about retroshare.us I have no idea.

**Comment by alfinal** [comment]
Thank you, @G10h4ck let's wait if @cavebeat and @drbob say something next days. Please, if you or somebody have more direct contact than the github ID please try to reach them, they were a great contributors of RetroSahre.

I just contacted to the e-mail provided in ```whois retroshare.us```.

@G10h4ck do you think that you could merge DOCU and WIKI links appearing at top of https://retroshare.cc/ ?

Also I realized that at the bottom of official https://retroshare.cc needs to:
 - [ ] remove from the list: Project Site, FAQ, Wiki, Web forums and Developer mailing list (I think)

**Comment by G10h4ck** [comment]
> @G10h4ck do you think that you could merge DOCU and WIKI links appearing at top of https://retroshare.cc/ ?

I think it is better you do a PR on https://github.com/RetroShare/retroshare.github.io ;)

**Comment by alfinal** [comment]
Ok, I can do it, but as I said I'm waiting confirmation from at least two official developers with same criteria.

Maybe somebody has some argument about having splited documentation one made from git and other one made from github.com wiki...

**Comment by csoler** [comment]
I'm all for it. The documentation (especially support page) on retroshare.cc still refers to pages on sourceforge.net although it shouldn't, etc. Just make a PR, if something's wrong in it, we'll ask for some changes, but we're very glad that you help in improving the website.
